spring:
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:192.168.137.128}:8081
      filter:
        enabled: true

logging:
  level:
    org.javaup: info
  pattern:
    dateformat: mm:ss.SSS

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,gateway"
  prometheus:
    metrics:
      export:
        enabled: true
